os: linux
language: node_js
node_js:
  - 10

branches:
  only:
    - master

install:
  - npm i -g firebase-tools
  - npm ci

script:
  - npm run lint

deploy:
  skip_cleanup: true
  provider: script
  script: npm run deploy
  on:
    branch: master

cache: npm
